Repository SteeltoeOSS/Steeltoe, pull requests merged in 2019-07, with the labels that each got.

#76 Fix for Tasks
  src/Connectors/src/Connector.EFCore/MigrateDbContextTask.cs
  src/Management/src/CloudFoundryTasks/CloudFoundryWebHostExtensions.cs
Labels: unscheduled

#75 .Wait() => .GetAwaiter().GetResult()
  src/Discovery/src/EurekaBase/DiscoveryClient.cs
Labels: unscheduled

#77 Backport PRs from master
  roadmaps/2.3.0.md
  src/Connectors/src/Connector.EFCore/MigrateDbContextTask.cs
  src/Management/src/TaskCore/TaskWebHostExtensions.cs
Labels: unscheduled

#81 Removed code that removes the "X-Forwarded-Proto" header.
  src/Security/src/Authentication.CloudFoundryOwin/ForwardedProtocolMiddleware.cs
Labels: unscheduled

#82 Update 2.3.0.md roadmap
  roadmaps/2.3.0.md
Labels: unscheduled

#84 Oracle DB Connector
  src/Connectors/src/Connector.EF6Autofac/OracleDbContextContainerBuilderExtensions.cs
  src/Connectors/src/Connector.EF6Core/OracleDbContextServiceCollectionExtensions.cs
  src/Connectors/src/Connector.EFCore/EntityFrameworkCoreTypeLocator.cs
  src/Connectors/src/Connector.EFCore/OracleDbContextOptionsExtensions.cs
  src/Connectors/src/ConnectorAutofac/OracleContainerBuilderExtensions.cs
  src/Connectors/src/ConnectorBase/Relational/Oracle/EF6/OracleDbContextConnectorFactory.cs
  src/Connectors/src/ConnectorBase/Relational/Oracle/OracleProviderConfigurer.cs
  src/Connectors/src/ConnectorBase/Relational/Oracle/OracleProviderConnectorFactory.cs
  src/Connectors/src/ConnectorBase/Relational/Oracle/OracleProviderConnectorOptions.cs
  src/Connectors/src/ConnectorBase/Relational/Oracle/OracleTypeLocator.cs
  src/Connectors/src/ConnectorBase/Relational/RelationalHealthContributor.cs
  src/Connectors/src/ConnectorBase/Steeltoe.CloudFoundry.ConnectorBase.csproj
  src/Connectors/src/ConnectorCore/OracleProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/OracleServiceCollectionExtensions.cs
  src/Connectors/test/Connector.EF6Autofac.Net4Test/GoodOracleDbContextcs.cs
  src/Connectors/test/Connector.EF6Autofac.Net4Test/OracleDbContextContainerBuilderExtensionsTest.cs
  src/Connectors/test/Connector.EF6Core.Net4Test/BadOracleDbContext.cs
  src/Connectors/test/Connector.EF6Core.Net4Test/GoodOracleDbContext.cs
  src/Connectors/test/Connector.EF6Core.Net4Test/OracleDbContextConnectorFactoryTest.cs
  src/Connectors/test/Connector.EF6Core.Net4Test/OracleDbContextServiceCollectionExtensionsTest.cs
  src/Connectors/test/Connector.EFCore.Test/EntityFrameworkCoreTypeLocatorTest.cs
  src/Connectors/test/Connector.EFCore.Test/OracleDbContextOptionsExtensionsTest.cs
  src/Connectors/test/Connector.EFCore.Test/Steeltoe.CloudFoundry.Connector.EFCore.Test.csproj
  src/Connectors/test/ConnectorAutofac.Test/OracleContainerBuilderExtensionsTest.cs
  src/Connectors/test/ConnectorAutofac.Test/Steeltoe.CloudFoundry.ConnectorAutofac.Test.csproj
  src/Connectors/test/ConnectorBase.Test/Relational/Oracle/OracleProviderConfigurerTest.cs
  src/Connectors/test/ConnectorBase.Test/Relational/Oracle/OracleProviderConnectorFactoryTest.cs
  src/Connectors/test/ConnectorBase.Test/Relational/Oracle/OracleProviderConnectorOptionsTest.cs
  src/Connectors/test/ConnectorBase.Test/Relational/Oracle/OracleTypeLocatorTest.cs
  src/Connectors/test/ConnectorBase.Test/Relational/RelationalHealthContributorTest.cs
  src/Connectors/test/ConnectorBase.Test/Steeltoe.CloudFoundry.ConnectorBase.Test.csproj
  src/Connectors/test/ConnectorCore.Test/OracleProviderServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/OracleServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/Steeltoe.CloudFoundry.ConnectorCore.Test.csproj
Labels: 2.x, Connectors, enhancement, unscheduled

#86 Light HttpClientHelper Tweaking
  src/Common/src/Common.Http/HttpClientHelper.cs
Labels: 2.x, Common, unscheduled

#87 Add support for DbMigrations endpoint
  .gitignore
  src/Management/src/EndpointBase/DbMigrations/DbMigrationsDescriptor.cs
  src/Management/src/EndpointBase/DbMigrations/DbMigrationsEndpoint.cs
  src/Management/src/EndpointBase/DbMigrations/DbMigrationsEndpointOptions.cs
  src/Management/src/EndpointBase/DbMigrations/IDbMigrationsOptions.cs
  src/Management/src/EndpointBase/IEndpointOptions.cs
  src/Management/src/EndpointBase/Properties/AssemblyInfo.cs
  src/Management/src/EndpointCore/DbMigrations/DbMigrationsEndpointMiddleware.cs
  src/Management/src/EndpointCore/DbMigrations/EndpointApplicationBuilderExtensions.cs
  src/Management/src/EndpointCore/DbMigrations/EndpointServiceCollectionExtensions.cs
  src/Management/test/EndpointBase.Test/BaseTest.cs
  src/Management/test/EndpointBase.Test/DbMigrations/DbMigrationsEndpointTests.cs
  src/Management/test/EndpointBase.Test/DbMigrations/MockDbContext.cs
  src/Management/test/EndpointBase.Test/DbMigrations/SomeDbException.cs
  src/Management/test/EndpointBase.Test/Steeltoe.Management.EndpointBase.Test.csproj
  src/Management/test/EndpointCore.Test/DbMigrations/EndpointMiddlewareTest.cs
  src/Management/test/EndpointCore.Test/DbMigrations/EndpointServiceCollectionTest.cs
  src/Management/test/EndpointCore.Test/DbMigrations/Startup.cs
  src/Management/test/EndpointCore.Test/Steeltoe.Management.EndpointCore.Test.csproj
Labels: unscheduled
