Repository SteeltoeOSS/Steeltoe, pull requests merged in 2019-06, with the labels that each got.

#41 Disable vault renewal
  src/Configuration/src/ConfigServerBase/ConfigServerClientSettings.cs
  src/Configuration/src/ConfigServerBase/ConfigServerClientSettingsOptions.cs
  src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs
  src/Configuration/src/ConfigServerBase/ConfigurationSettingsHelper.cs
  src/Configuration/test/ConfigServerBase.Test/ConfigServerConfigurationProviderTest.cs
  src/Configuration/test/ConfigServerCore.Test/ConfigServerConfigurationBuilderExtensionsCoreTest.cs
Labels: unscheduled

#51 Update readme roadmap
  CONTRIBUTING.md
  README.md
  azure-pipelines.yml
  project-docs/code-maintainers.md
  project-docs/contributing-workflow.md
  project-docs/project-list.md
  roadmaps/2.3.0.md
Labels: unscheduled

#52 Merge forward to master
  CONTRIBUTING.md
  README.md
  project-docs/code-maintainers.md
  project-docs/contributing-workflow.md
  project-docs/project-list.md
  roadmaps/2.3.0.md
  src/Configuration/src/ConfigServerBase/ConfigServerClientSettings.cs
  src/Configuration/src/ConfigServerBase/ConfigServerClientSettingsOptions.cs
  src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs
  src/Configuration/src/ConfigServerBase/ConfigurationSettingsHelper.cs
  src/Configuration/test/ConfigServerBase.Test/ConfigServerConfigurationProviderTest.cs
  src/Configuration/test/ConfigServerCore.Test/ConfigServerConfigurationBuilderExtensionsCoreTest.cs
Labels: unscheduled

#42 Update DataProtection for StackExchange.Redis 2.0+
  src/Security/Security.sln
  src/Security/src/DataProtection.RedisCore/CloudFoundryRedisXmlRepository.cs
  src/Security/src/DataProtection.RedisCore/Steeltoe.Security.DataProtection.RedisCore.csproj
  versions.props
Labels: unscheduled

#53 Merge master into 2x
  azure-pipelines.yml
  src/Common/src/Common/Extensions/UriExtensions.cs
  src/Common/test/Common.Test/Extensions/UriExtensionsTest.cs
  src/Discovery/src/EurekaBase/DiscoveryClient.cs
  src/Discovery/src/EurekaBase/Transport/EurekaHttpClient.cs
  src/Security/Security.sln
  src/Security/src/Authentication.CloudFoundryBase/TokenExchanger.cs
  src/Security/src/DataProtection.RedisCore/CloudFoundryRedisXmlRepository.cs
  src/Security/src/DataProtection.RedisCore/Steeltoe.Security.DataProtection.RedisCore.csproj
  versions.props
Labels: unscheduled

#50 Fix issue #34
  src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
  src/Configuration/src/ConfigServerBase/ConfigurationSettingsHelper.cs
  src/Configuration/test/CloudFoundryBase.Test/CloudFoundryConfigurationBuilderExtensionsTest.cs
  src/Configuration/test/CloudFoundryBase.Test/CloudfoundryConfigurationProviderTest.cs
  src/Discovery/src/EurekaBase/EurekaPostConfigurer.cs
Labels: unscheduled

#49 Add a codecov.yml file
  codecov.yml
Labels: unscheduled

#55 Merge serilog pr
  src/Logging/Logging.sln
  src/Logging/src/SerilogDynamicLogger/SerilogBuilderExtensions.cs
  src/Logging/src/SerilogDynamicLoggerCore/ISerilogOptions.cs
  src/Logging/src/SerilogDynamicLoggerCore/SerilogBuilderExtensions.cs
  src/Logging/src/SerilogDynamicLoggerCore/SerilogDynamicLoggerFactory.cs
  src/Logging/src/SerilogDynamicLoggerCore/SerilogDynamicProvider.cs
  src/Logging/src/SerilogDynamicLoggerCore/SerilogOptions.cs
  src/Logging/src/SerilogDynamicLoggerCore/Steeltoe.Extensions.Logging.SerilogDynamicLoggerCore.csproj
  src/Logging/test/SerilogDynamicLoggerCore.Test/ConsoleOutputBorrower.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/SerilogDynamicLoggerConfigurationExtensionsTest.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/SerilogDynamicLoggerProviderTest.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/SerilogDynamicLoggingBuilderTest.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/SerilogDynamicWebhostBuilderTest.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/Steeltoe.Extensions.Logging.SerilogDynamicLoggerCore.Test.csproj
  src/Logging/test/SerilogDynamicLoggerCore.Test/TestClass.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/TestServerStartup.cs
  src/Logging/test/SerilogDynamicLoggerCore.Test/TestSink.cs
Labels: unscheduled

#54 Fix context path for OWIN running in virtual directory
  src/Management/src/EndpointOwin/CloudFoundry/CloudFoundryEndpointOwinMiddleware.cs
Labels: unscheduled

#46 Address potential CWE 117 in EndpointBase
  src/Common/src/Common/SecurityUtilities.cs
  src/Common/test/Common.Test/SecurityUtilitiesTest.cs
  src/Management/Management.sln
  src/Management/src/EndpointBase/CloudFoundry/SecurityBase.cs
  src/Management/src/EndpointBase/Loggers/LoggersChangeRequest.cs
  src/Management/src/EndpointBase/Loggers/LoggersEndpoint.cs
  src/Management/src/EndpointBase/Metrics/Observer/HttpClientCoreObserver.cs
  src/Management/src/EndpointBase/Metrics/Observer/HttpClientDesktopObserver.cs
Labels: scheduled

#61 Postgres connector support for search path
  src/Connectors/src/ConnectorBase/Relational/PostgreSQL/PostgresProviderConnectorOptions.cs
  src/Connectors/test/ConnectorBase.Test/Relational/PostgreSQL/PostgresProviderConnectorOptionsTest.cs
Labels: unscheduled

#60 new Trace level logging for OWIN Security [delivers #166524145]
  src/Security/src/Authentication.CloudFoundryBase/TokenExchanger.cs
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIdConnectAuthenticationHandler.cs
Labels: unscheduled

#62 Change CloudFoundryTasks to TaskCore
  src/Common/src/Common/Tasks/IApplicationTask.cs
  src/Management/Management.sln
  src/Management/src/CloudFoundryCore/CloudFoundryServiceCollectionExtensions.cs
  src/Management/src/TaskCore/DelegatingTask.cs
  src/Management/src/TaskCore/Steeltoe.Management.TaskCore.csproj
  src/Management/src/TaskCore/TaskServiceCollectionExtensions.cs
  src/Management/src/TaskCore/TaskWebHostExtensions.cs
  src/Management/test/ExporterBase.Test/Tracing/Zipkin/TraceExporterOptionsTest.cs
  src/Management/test/TaskCore.Test/Steeltoe.Management.TaskCore.Test.csproj
  src/Management/test/TaskCore.Test/TaskRunTest.cs
  src/Management/test/TracingBase.Test/TracingOptionsTest.cs
Labels: unscheduled

#57 Microsoft HealthChecks: Remove 3rd Party Deps, add tests
  src/Connectors/src/ConnectorBase/Cache/RedisConnectionInfo.cs
  src/Connectors/src/ConnectorBase/ConnectionStringManager.cs
  src/Connectors/src/ConnectorBase/DocumentDB/MongoDb/MongoDbConnectionInfo.cs
  src/Connectors/src/ConnectorBase/IConnectionInfo.cs
  src/Connectors/src/ConnectorBase/Queue/RabbitMQConnectionInfo.cs
  src/Connectors/src/ConnectorBase/Relational/MySql/MySqlConnectionInfo.cs
  src/Connectors/src/ConnectorBase/Relational/PostgreSQL/PostgresConnectionInfo.cs
  src/Connectors/src/ConnectorBase/Relational/SqlServer/SqlServerConnectionInfo.cs
  src/Connectors/src/ConnectorCore/MongoDbProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/MySqlProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/PostgresProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/RabbitMQProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/RedisCacheServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/SqlServerProviderServiceCollectionExtensions.cs
  src/Connectors/src/ConnectorCore/Steeltoe.CloudFoundry.ConnectorCore.csproj
  src/Connectors/test/ConnectorCore.Test/ConnectionStringManagerTest.cs
  src/Connectors/test/ConnectorCore.Test/MongoDbProviderServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/MySqlProviderServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/PostgresProviderServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/RabbitMQServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/RedisCacheServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/SqlServerProviderServiceCollectionExtensionsTest.cs
  src/Connectors/test/ConnectorCore.Test/Steeltoe.CloudFoundry.ConnectorCore.Test.csproj
  src/Management/src/EndpointCore/Health/HealthRegistrationsAggregator.cs
  versions.props
Labels: unscheduled

#64 Correctly set NuGet Package version
  azure-pipelines.yml
Labels: unscheduled

#63 Ensure TLS Ports are picked as default, if provided in the creds
  src/Connectors/src/ConnectorBase/Services/RedisServiceInfo.cs
  src/Connectors/src/ConnectorBase/Services/RedisServiceInfoFactory.cs
  src/Connectors/src/ConnectorBase/Services/ServiceInfoFactory.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisCacheConfigurerTest.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisServiceConnectorFactoryTest.cs
  src/Connectors/test/ConnectorBase.Test/Services/RedisServiceInfoFactoryTest.cs
  src/Connectors/test/ConnectorBase.Test/Services/RedisServiceInfoTest.cs
Labels: Connectors, unscheduled

#66 Update 2.3.0.md Roadmap
  roadmaps/2.3.0.md
Labels: unscheduled

#68 sign nupkg and snupkg
  build/sign-packages.ps1
Labels: unscheduled

#72 Add a test for consul tag to metadata mapping
  src/Discovery/test/ConsulBase.Test/Registry/ConsulRegistrationTest.cs
Labels: unscheduled

#71 Add the missing `.ConfigureAwait(false)`
  roadmaps/2.3.0.md
  sharedproject.props
  src/CircuitBreaker/src/Hystrix.MetricsEventsCore/Controllers/HystrixStreamBaseController.cs
  src/CircuitBreaker/src/HystrixBase/HystrixCollapser.cs
  src/CircuitBreaker/src/HystrixBase/HystrixCommand.cs
  src/CircuitBreaker/src/HystrixCore/HystrixRequestContextMiddleware.cs
  src/CircuitBreaker/src/HystrixCore/HystrixRequestContextMiddlewareOwin.cs
  src/CircuitBreaker/test/Hystrix.MetricsEventsCore.Test/Controllers/HystrixConfigStreamControllerTest.cs
  src/CircuitBreaker/test/Hystrix.MetricsEventsCore.Test/Controllers/HystrixMetricsStreamControllerTest.cs
  src/CircuitBreaker/test/Hystrix.MetricsEventsCore.Test/Controllers/HystrixRequestEventStreamControllerTest.cs
  src/CircuitBreaker/test/Hystrix.MetricsEventsCore.Test/Controllers/HystrixUtilizationStreamControllerTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCommandTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixRequestCacheTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Strategy/Concurrency/HystrixQueuedTaskSchedulerTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Strategy/Concurrency/HystrixSyncTaskSchedulerTest.cs
  src/Common/src/Common.Http/Discovery/DiscoveryHttpClientHandlerBase.cs
  src/Common/test/Common.Net.Test/WindowsNetworkFileShareTest.cs
  src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisCacheConfigurerTest.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisCacheConnectorOptionsTest.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisServiceConnectorFactoryTest.cs
  src/Connectors/test/ConnectorBase.Test/Cache/RedisTypeLocatorTest.cs
  src/Discovery/src/ConsulBase/Discovery/ConsulDiscoveryClient.cs
  src/Discovery/src/ConsulBase/Discovery/ConsulHealthContributor.cs
  src/Discovery/src/ConsulBase/Discovery/TtlScheduler.cs
  src/Discovery/src/ConsulBase/Registry/ConsulServiceRegistry.cs
  src/Discovery/src/EurekaBase/DiscoveryClient.cs
  src/Discovery/src/EurekaBase/EurekaClientService.cs
  src/Discovery/src/EurekaBase/Transport/EurekaHttpClient.cs
  src/Management/src/Diagnostics/Microsoft/GCRoot.cs
  src/Management/src/EndpointCore/Health/HealthRegistrationsAggregator.cs
  src/Management/src/EndpointWeb/Handler/ActuatorHandler.cs
  src/Management/src/ExporterBase/Metrics/CloudFoundryForwarder/CloudFoundryForwarderExporter.cs
  src/Management/src/ExporterBase/Tracing/Zipkin/TraceExporterHandler.cs
  src/Security/src/Authentication.CloudFoundryBase/CloudFoundryTokenKeyResolver.cs
  src/Security/src/Authentication.CloudFoundryWcf/CloudFoundryTokenKeyResolver.cs
  src/Security/src/Authentication.CloudFoundryWcf/JwtHeaderMessageInspector.cs
  src/Security/src/DataProtection.CredHubBase/CredHubClient.cs
  versions.props
Labels: unscheduled
