Repository SteeltoeOSS/Steeltoe, pull requests merged in 2019-08, with the labels that each got.

#88 Hystrix tests
  azure-pipelines.yml
  src/CircuitBreaker/src/HystrixBase/HystrixCommand.cs
  src/CircuitBreaker/src/HystrixBase/HystrixRequestLog.cs
  src/CircuitBreaker/src/HystrixBase/Strategy/Concurrency/HystrixTaskScheduler.cs
  src/CircuitBreaker/src/HystrixBase/Util/SemaphoreSlimExtensions.cs
  src/CircuitBreaker/src/HystrixBase/Util/TimerReference.cs
  src/CircuitBreaker/test/HystrixBase.Test/Config/HystrixConfigurationStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCircuitBreakerTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCollapserTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCommandMetricsTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCommandTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCommandTimeoutConcurrencyTesting.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixThreadPoolMetricsTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixThreadPoolOptionsTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/CommandStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/CumulativeCollapserEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/CumulativeCommandEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/CumulativeThreadPoolEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/HealthCountsStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/HystrixDashboardStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingCollapserBatchSizeDistributionStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingCollapserEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingCommandEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingCommandLatencyDistributionStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingCommandMaxConcurrencyStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingThreadPoolEventCounterStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Consumer/RollingThreadPoolMaxConcurrencyStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/HystrixThreadEventStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Metric/Sample/HystrixUtilizationStreamTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Util/HystrixTimerTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Util/TimeTest.cs
  src/CircuitBreaker/test/HystrixBase.Test/Util/TimerReferenceTest.cs
  src/Common/test/Common.Security.Test/PemConfigurationExtensionsTest.cs
  src/Configuration/test/ConfigServerBase.Test/ConfigServerConfigurationProviderTest.cs
  src/Discovery/test/EurekaBase.Test/DiscoveryClientTest.cs
  src/Management/src/EndpointBase/DbMigrations/DbMigrationsEndpoint.cs
  src/Management/test/EndpointBase.Test/DbMigrations/DbMigrationsEndpointTests.cs
  src/Management/test/EndpointBase.Test/Metrics/Observer/HttpClientCoreObserverTest.cs
  src/Management/test/EndpointBase.Test/Metrics/Observer/HttpClientDesktopObserverTest.cs
  src/Management/test/EndpointCore.Test/Metrics/Observer/AspNetCoreHostingObserverTest.cs
  versions.props
Labels: unscheduled

#93 recognize vcap setting p.config-server for scs3.0
  src/Configuration/Configuration.sln.DotSettings
  src/Configuration/src/ConfigServerBase/ConfigurationSettingsHelper.cs
  src/Configuration/test/ConfigServerCore.Test/ConfigServerConfigurationBuilderExtensionsCoreTest.cs
Labels: unscheduled

#96 Update roadmaps for 2.3.0 and 3.0.0
  roadmaps/2.3.0.md
  roadmaps/3.0.0.md
Labels: unscheduled

#89 Consistent token validation params
  src/Security/src/Authentication.CloudFoundryBase/CloudFoundryHelper.cs
  src/Security/src/Authentication.CloudFoundryCore/CloudFoundryJwtBearerConfigurer.cs
  src/Security/src/Authentication.CloudFoundryCore/CloudFoundryOpenIdConnectConfigurer.cs
  src/Security/src/Authentication.CloudFoundryCore/CloudFoundryOpenIdConnectOptions.cs
  src/Security/test/Authentication.CloudFoundryBase.Test/CloudFoundryHelperTest.cs
Labels: 2.x, Security, unscheduled

#95 Remove obsolete OpenID* classes (most renamed OpenId*) fixes #38
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIDConnectExtension.cs
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIDTokenResponse.cs
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIdConnectAuthenticationHandler.cs
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIdConnectOptions.cs
  src/Security/test/Authentication.CloudFoundryOwin.Net4Test/OpenIdConnect/OpenIdConnectConfigurerTest.cs
  src/Security/test/Authentication.CloudFoundryOwin.Net4Test/UriUtilityTest.cs
Labels: unscheduled

#103 Update Pipeline to set FileVersion as expected
  azure-pipelines.yml
  sharedproject.props
  versions.props
Labels: 2.x, bug, scheduled

#104 Allow more configuration of Open Id Connect Options #97
  src/Security/src/Authentication.CloudFoundryCore/CloudFoundryExtensions.cs
Labels: 2.x, Security, enhancement, in progress

#106 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-or-enhancement-request.md
  .github/ISSUE_TEMPLATE/security-vulnerability-report.md
Labels: unscheduled

#110 PathBase needed when determining redirect_uri
  src/Security/src/Authentication.CloudFoundryOwin/OpenIdConnect/OpenIdConnectAuthenticationHandler.cs
  src/Security/src/Authentication.CloudFoundryOwin/UriUtility.cs
Labels: unscheduled

#111 Resolve new build failure
  .ionide/symbolCache.db
  src/Connectors/EnableGemFire.ps1
Labels: unscheduled
