Repository SteeltoeOSS/Steeltoe, pull requests merged in 2021-01, with the labels that each got.

#562 Update Coverlet and SonarAnalyzer
  nuget.config
  src/CircuitBreaker/src/Hystrix.MetricsStreamCore/RabbitMetricsStreamPublisher.cs
  src/Common/src/Common.Http/HttpClientHelper.cs
  src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
  src/Connectors/src/ConnectorCore/RedisCacheServiceCollectionExtensions.cs
  src/Integration/src/IntegrationBase/StaticMessageHeaderAccessor.cs
  src/Management/src/OpenTelemetryBase/Metrics/Processor/SteeltoeProcessor.cs
  src/Management/test/EndpointCore.Test/Health/EndpointMiddlewareTest.cs
  src/Messaging/src/RabbitMQ/Listener/DirectMessageListenerContainer.cs
  src/Messaging/src/RabbitMQ/Support/Converter/SimpleMessageConverter.cs
  src/Security/src/Authentication.CloudFoundryBase/CloudFoundryHelper.cs
  versions.props
Labels: ReleaseLine/3.x, Type/enhancement

#567 update build version to 2.5.3*
  azure-pipelines.yml
Labels: ReleaseLine/2.x

#568 update build version to 3.1.0*
  azure-pipelines.yml
Labels: ReleaseLine/3.x

#560 Improve management endpoint mapping
  src/Management/src/EndpointCore/ActuatorRouteBuilderExtensions.cs
  src/Management/src/EndpointCore/CloudFoundry/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/DbMigrations/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Env/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Extensions/ServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Health/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Hypermedia/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Info/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Internal/EndpointMappingEntry.cs
  src/Management/src/EndpointCore/Loggers/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Mappings/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Metrics/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Refresh/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/ThreadDump/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Trace/EndpointServiceCollectionExtensions.cs
Labels: Component/Management, ReleaseLine/3.x

#554 Split actuator service registration
  src/Management/src/EndpointBase/CloudFoundry/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/DbMigrations/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Env/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Health/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/HeapDump/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Hypermedia/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Info/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Loggers/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Mappings/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Metrics/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Refresh/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Steeltoe.Management.EndpointBase.csproj
  src/Management/src/EndpointBase/ThreadDump/ServiceCollectionExtensions.cs
  src/Management/src/EndpointBase/Trace/ServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/ActuatorRouteBuilderExtensions.cs
  src/Management/src/EndpointCore/ActuatorServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/CloudFoundry/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/DbMigrations/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Env/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Health/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Hypermedia/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Info/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Loggers/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Mappings/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Metrics/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Refresh/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/ThreadDump/EndpointServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/Trace/EndpointServiceCollectionExtensions.cs
  src/Management/test/EndpointBase.Test/CloudFoundry/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/DbMigrations/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Env/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Health/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/HeapDump/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Hypermedia/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Info/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Loggers/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Mappings/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Metrics/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Refresh/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/ThreadDump/ServiceCollectionTests.cs
  src/Management/test/EndpointBase.Test/Trace/ServiceCollectionTests.cs
  src/Management/test/EndpointCore.Test/Hypermedia/EndpointMiddlewareTest.cs
Labels: Component/Management, ReleaseLine/3.x

#574 Configure a proper HttpClient Timeout - Fix #571
  src/Security/src/Authentication.CloudFoundryBase/CloudFoundryTokenKeyResolver.cs
  src/Security/test/Authentication.CloudFoundryBase.Test/CloudFoundryTokenKeyResolverTest.cs
Labels: Component/Security, ReleaseLine/3.x, Type/bug

#573 Changes to integrate service container with expressions
  src/Common/src/Abstractions/Contexts/IApplicationContext.cs
  src/Common/src/Abstractions/Expression/Contexts/IServiceExpressionContext.cs
  src/Common/src/Abstractions/Expression/Contexts/IServiceExpressionResolver.cs
  src/Common/src/Abstractions/Util/IStringValueResolver.cs
  src/Common/src/Common.Expression/Contexts/ConfigurationAccessor.cs
  src/Common/src/Common.Expression/Contexts/DictionaryAccessor.cs
  src/Common/src/Common.Expression/Contexts/ServiceExpressionContext.cs
  src/Common/src/Common.Expression/Contexts/ServiceExpressionContextAccessor.cs
  src/Common/src/Common.Expression/Contexts/ServiceFactoryAccessor.cs
  src/Common/src/Common.Expression/Contexts/ServiceFactoryResolver.cs
  src/Common/src/Common.Expression/Contexts/StandardServiceExpressionResolver.cs
  src/Common/src/Common.Expression/Spring/Ast/ServiceReference.cs
  src/Common/src/Common.Expression/Spring/SpelMessage.cs
  src/Common/src/Common.Expression/Spring/Standard/InternalSpelExpressionParser.cs
  src/Common/src/Common.Expression/Spring/Standard/TokenKind.cs
  src/Common/src/Common.Expression/Spring/Standard/Tokenizer.cs
  src/Common/src/Common.Expression/Spring/Support/StandardEvaluationContext.cs
  src/Common/src/Common/Configuration/PropertyPlaceHolderHelper.cs
  src/Common/src/Common/Contexts/AbstractApplicationContext.cs
  src/Common/test/Common.Expression.Test/Contexts/ApplicationContextExpressionTests.cs
  src/Common/test/Common.Expression.Test/Contexts/ConfigurationAccessorTests.cs
  src/Common/test/Common.Expression.Test/Contexts/DictionaryAcessorTests.cs
  src/Common/test/Common.Expression.Test/Contexts/ServiceFactoryAccessorTests.cs
  src/Common/test/Common.Expression.Test/Spring/EvaluationTests.cs
  src/Common/test/Common.Expression.Test/Spring/SpelReproTests.cs
  src/Messaging/test/RabbitMQ.Test/Core/RabbitAdminTest.cs
Labels: ReleaseLine/3.x
