Repository SteeltoeOSS/Steeltoe, pull requests merged in 2022-08, with the labels that each got.

#965 Add tools for automated code cleanup
  .config/dotnet-tools.json
  build/pr-code-cleanup.yml
  build/verify-code-style.yml
  cleanupcode.ps1
Labels: Type/code-quality

#978 Fix type and member naming
  Steeltoe.Debug.ruleset
  Steeltoe.Release.ruleset
  build/circuitbreaker.yml
  build/common.yml
  build/configuration.yml
  build/connectors.yml
  build/discovery.yml
  build/integration.yml
  build/logging.yml
  build/management.yml
  build/messaging.yml
  build/security.yml
  build/stream.yml
  shared.props
  src/Bootstrap/src/Autoconfig/HostBuilderExtensions.cs
  src/Bootstrap/src/Autoconfig/WebHostBuilderExtensions.cs
  src/CircuitBreaker/src/HystrixBase/Strategy/HystrixPlugins.cs
  src/CircuitBreaker/src/HystrixBase/Util/HystrixRollingNumber.cs
  src/CircuitBreaker/src/HystrixBase/Util/HystrixRollingPercentile.cs
  src/CircuitBreaker/test/HystrixBase.Test/HystrixCollapserTest.cs
  src/Common/src/Common.Expression/Spring/Standard/Tokenizer.cs
  src/Common/src/Common.Kubernetes/KubernetesClientHelpers.cs
  src/Common/src/Common.Net/WindowsNetworkFileShare.cs
  src/Common/src/Common/Platform.cs
  src/Common/test/Common.Expression.Test/Spring/ConstructorInvocationTests.cs
  src/Common/test/Common.Expression.Test/Spring/EvaluationTests.cs
  src/Common/test/Common.Expression.Test/Spring/PerformanceTests.cs
  src/Common/test/Common.Expression.Test/Spring/SpelCompilationCoverageTests.cs
  src/Common/test/Common.Expression.Test/Spring/SpelCompilationPerformanceTests.cs
  src/Common/test/Common.Expression.Test/Spring/SpelReproTests.cs
  src/Common/test/Common.Expression.Test/Spring/Support/ReflectionHelperTests.cs
  src/Common/test/Common.Expression.Test/Spring/TestResources/Inventor.cs
  src/Common/test/Common.Expression.Test/Spring/TestResources/le/div/mod/reserved/Reserver.cs
  src/Configuration/src/KubernetesBase/KubernetesConfigMapProvider.cs
  src/Configuration/src/KubernetesBase/KubernetesConfigMapSource.cs
  src/Configuration/src/KubernetesBase/KubernetesConfigurationBuilderExtensions.cs
  src/Configuration/src/KubernetesBase/KubernetesProviderBase.cs
  src/Configuration/src/KubernetesBase/KubernetesSecretProvider.cs
  src/Configuration/src/KubernetesBase/KubernetesSecretSource.cs
  src/Configuration/test/ConfigServer.Integration.Test/ConfigServerConfigurationExtensionsIntegrationTest.cs
  src/Configuration/test/ConfigServer.Integration.Test/HomeController.cs
  src/Configuration/test/ConfigServerCore.Test/ConfigServerConfigurationBuilderExtensionsCoreTest.cs
  src/Connectors/src/ConnectorBase/PostgreSQL/PostgresProviderConfigurer.cs
  src/Discovery/test/Eureka.Test/EurekaDiscoveryClientBuilderExtensionsTest.cs
  src/Discovery/test/Eureka.Test/EurekaPostConfigurerTest.cs
  src/Discovery/test/Kubernetes.Test/Discovery/KubernetesDiscoveryClientTest.cs
  src/Logging/src/DynamicLogger/DynamicConsoleLoggerProvider.cs
  src/Management/src/EndpointBase/Hypermedia/Links.cs
  src/Management/src/EndpointBase/SpringBootAdminClient/ServiceCollectionExtensions.cs
  src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs
  src/Security/src/Authentication.MtlsCore/LoggingExtensions.cs
  src/Stream/test/BinderRabbitMQ.Test/Poco.cs
Labels: Warn/breaking-change, Type/code-quality

#986 Add StructuredMessageProcessingLogger
  src/Logging/src/Abstractions/DynamicLoggerProviderBase.cs
  src/Logging/src/Abstractions/MessageProcessingLogger.cs
  src/Logging/src/Abstractions/Properties/AssemblyInfo.cs
  src/Logging/src/Abstractions/StructuredMessageProcessingLogger.cs
  src/Logging/src/DynamicSerilogBase/SerilogDynamicProvider.cs
  src/Logging/test/DynamicSerilogBase.Test/SerilogDynamicLoggerProviderTest.cs
  src/Logging/test/DynamicSerilogBase.Test/serilogSettings.json
Labels: Type/bug, ReleaseLine/3.x, Component/Logging

#992 Fix hanging Resharper/Rider testrunner when tests fail
  src/Management/test/Kubernetes.Test/HostBuilderExtensionsTest.cs
  src/Messaging/test/RabbitMQ.Test/Connection/ConnectionFactoryLifecycleTest.cs
  src/Messaging/test/RabbitMQ.Test/Core/RabbitAdminTest.cs
  src/Messaging/test/RabbitMQ.Test/Listener/ContainerShutDownTest.cs
  src/Stream/test/BinderRabbitMQ.Test/RabbitBinderTests.cs
Labels: Type/code-quality

#993 Remove obsolete types and members
  src/CircuitBreaker/src/Hystrix.MetricsEvents/HystrixApplicationBuilderExtensions.cs
  src/CircuitBreaker/src/Hystrix.MetricsEvents/HystrixServiceCollectionExtensions.cs
  src/CircuitBreaker/src/Hystrix.MetricsStream/HystrixApplicationBuilderExtensions.cs
  src/CircuitBreaker/src/Hystrix.MetricsStream/HystrixServiceCollectionExtensions.cs
  src/CircuitBreaker/test/Hystrix.MetricsStream.Test/HystrixApplicationBuilderExtensionsTest.cs
  src/Common/src/Common.Http/ClientCertificateHttpHandlerProvider.cs
  src/Common/src/Common.Http/LoadBalancer/LoadBalancerDelegatingHandler.cs
  src/Common/src/Common.Http/LoadBalancer/LoadBalancerHttpClientHandler.cs
  src/Common/src/Common.Kubernetes/ServiceCollectionExtensions.cs
  src/Common/src/Common/ServiceCollectionExtensions.cs
  src/Common/src/Common/Util/ObjectUtils.cs
  src/Common/test/Common.Kubernetes.Test/ServiceCollectionExtensionsTest.cs
  src/Configuration/src/Abstractions/ServiceCollectionExtensions.cs
  src/Configuration/src/CloudFoundry/CloudFoundryHostBuilderExtensions.cs
  src/Configuration/src/ConfigServer/ConfigServerClientSettings.cs
  src/Configuration/src/ConfigServer/ConfigServerConfigurationBuilderExtensionsCore.cs
  src/Configuration/src/ConfigServer/ConfigServerConfigurationProvider.cs
  src/Configuration/src/ConfigServer/ConfigServerServiceCollectionExtensions.cs
  src/Configuration/test/ConfigServer.Test/ConfigServerConfigurationProviderTest.cs
  src/Configuration/test/ConfigServer.Test/ConfigServerServiceCollectionExtensionsTest.cs
  src/Discovery/src/Client/DiscoveryApplicationBuilderExtensions.cs
  src/Discovery/src/Client/DiscoveryClientStartupFilter.cs
  src/Discovery/src/Client/DiscoveryServiceCollectionExtensions.cs
  src/Logging/src/DynamicSerilog/ISerilogOptions.cs
  src/Logging/src/DynamicSerilog/SerilogHostBuilderExtensions.cs
  src/Logging/src/DynamicSerilog/SerilogLoggingBuilderExtensions.cs
  src/Logging/src/DynamicSerilog/SerilogOptions.cs
  src/Logging/src/DynamicSerilog/SerilogWebHostBuilderExtensions.cs
  src/Management/src/Endpoint/ActuatorRouteBuilderExtensions.cs
  src/Management/src/Endpoint/ActuatorServiceCollectionExtensions.cs
  src/Management/src/Endpoint/CloudFoundry/CloudFoundryActuatorStartupFilter.cs
  src/Management/src/Endpoint/DbMigrations/DbMigrationsStartupFilter.cs
  src/Management/src/Endpoint/Env/EnvStartupFilter.cs
  src/Management/src/Endpoint/Extensions/ServiceCollectionExtensions.cs
  src/Management/src/Endpoint/Health/HealthStartupFilter.cs
  src/Management/src/Endpoint/HeapDump/HeapDumpStartupFilter.cs
  src/Management/src/Endpoint/HeapDump/LinuxHeapDumper.cs
  src/Management/src/Endpoint/Hypermedia/HypermediaStartupFilter.cs
  src/Management/src/Endpoint/Info/InfoStartupFilter.cs
  src/Management/src/Endpoint/Loggers/LoggersStartupFilter.cs
  src/Management/src/Endpoint/Mappings/MappingsStartupFilter.cs
  src/Management/src/Endpoint/Metrics/MetricsStartupFilter.cs
  src/Management/src/Endpoint/Metrics/Observer/GCEventsListener.cs
  src/Management/src/Endpoint/Metrics/Observer/ThreadPoolEventsListener.cs
  src/Management/src/Endpoint/Refresh/RefreshStartupFilter.cs
  src/Management/src/Endpoint/ThreadDump/ThreadDumpStartupFilter.cs
  src/Management/src/Endpoint/Trace/TraceStartupFilter.cs
  src/Management/src/Kubernetes/KubernetesActuatorsStartupFilter.cs
  src/Management/test/Endpoint.Test/Metrics/Observer/HttpClientCoreObserverTest.cs
  src/Management/test/Endpoint.Test/Metrics/Observer/HttpClientDesktopObserverTest.cs
  src/Management/test/Endpoint.Test/Metrics/PrometheusEndpointMiddlewareTest.cs
  src/Security/src/Authentication.CloudFoundry/ApplicationBuilderExtensions.cs
  src/Security/src/Authentication.CloudFoundry/ServiceCollectionExtensions.cs
  src/Security/src/Authentication.Mtls/CertificateApplicationBuilderExtensions.cs
Labels: Type/code-quality

#994 Remove unused parameters in non-exposed methods
  Steeltoe.Release.ruleset
  src/Bootstrap/src/Autoconfig/WebApplicationBuilderExtensions.cs
  src/CircuitBreaker/src/Hystrix/CircuitBreaker/HystrixCircuitBreakerFactory.cs
  src/CircuitBreaker/src/Hystrix/CircuitBreaker/HystrixCircuitBreakerImpl.cs
  src/CircuitBreaker/src/Hystrix/Config/HystrixCollapserConfiguration.cs
  src/CircuitBreaker/src/Hystrix/HystrixCommandMetrics.cs
  src/CircuitBreaker/test/Hystrix.MetricsEvents.Test/EventSources/HystrixEventSourceServiceTests.cs
  src/CircuitBreaker/test/Hystrix.Test/HystrixCollapserTest.cs
  src/CircuitBreaker/test/Hystrix.Test/HystrixCommandTest.cs
  src/CircuitBreaker/test/Hystrix.Test/InterruptibleCommand.cs
  src/CircuitBreaker/test/Hystrix.Test/Strategy/Concurrency/HystrixQueuedTaskSchedulerTest.cs
  src/CircuitBreaker/test/Hystrix.Test/Strategy/Concurrency/HystrixSyncTaskSchedulerTest.cs
  src/Common/src/Common/Converter/DictionaryToDictionaryConverter.cs
  src/Common/test/Common.Expression.Test/Spring/SpelCompilationCoverageTests.cs
  src/Configuration/test/Placeholder.Test/TestServerStartup1.cs
  src/Discovery/src/Eureka/Transport/EurekaHttpClient.cs
  src/Integration/src/RabbitMQ/Support/MappingUtils.cs
  src/Management/src/Endpoint/Metrics/Observer/CLRRuntimeObserver.cs
  src/Management/src/Endpoint/Metrics/Observer/EventSourceListener.cs
  src/Management/test/Endpoint.Test/Health/EndpointMiddlewareTest.cs
  src/Management/test/Endpoint.Test/Metrics/MetricsEndpointMiddlewareTest.cs
  src/Messaging/src/RabbitMQ/Config/RabbitListenerAttributeProcessor.cs
  src/Messaging/src/RabbitMQ/Connection/SimpleResourceHolder.cs
  src/Messaging/test/RabbitMQ.Test/Core/FixedReplyQueueDeadLetterTest.cs
  src/Messaging/test/RabbitMQ.Test/Listener/Adapters/MessagingMessageListenerAdapterTest.cs
  src/Security/test/DataProtection.CredHub.Test/CredHubClientTests.cs
Labels: Type/code-quality

#996 Use AttributeUsageAttribute (S3993) and seal attributes (S4060)
  Steeltoe.Debug.ruleset
  Steeltoe.Release.ruleset
  src/Common/src/Abstractions/Attributes/ServiceAttribute.cs
  src/Common/test/Common.Expression.Test/Spring/MethodInvocationTests.cs
  src/Connectors/src/Abstractions/ConnectionInfoAssemblyAttribute.cs
  src/Connectors/src/Abstractions/ServiceInfoFactoryAssemblyAttribute.cs
  src/Integration/src/Integration/Attributes/EndpointIdAttribute.cs
  src/Integration/src/Integration/Attributes/PayloadsAttribute.cs
  src/Integration/src/Integration/Attributes/ServiceActivatorAttribute.cs
  src/Integration/test/Integration.Test/Handler/MethodInvokingMessageProcessorAnnotationTest.cs
  src/Messaging/src/Abstractions/Handler/Attributes/DestinationVariableAttribute.cs
  src/Messaging/src/Abstractions/Handler/Attributes/HeaderAttribute.cs
  src/Messaging/src/Abstractions/Handler/Attributes/HeadersAttribute.cs
  src/Messaging/src/Abstractions/Handler/Attributes/MessageExceptionHandlerAttribute.cs
  src/Messaging/src/Abstractions/Handler/Attributes/PayloadAttribute.cs
  src/Messaging/src/Abstractions/Handler/Attributes/SendToAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/DeclareAnonymousQueueAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/DeclareExchangeAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/DeclareQueueAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/DeclareQueueBaseAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/DeclareQueueBindingAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/RabbitHandlerAttribute.cs
  src/Messaging/src/RabbitMQ/Attributes/RabbitListenerAttribute.cs
  src/Messaging/src/RabbitMQ/Listener/Adapters/DelegatingInvocableHandler.cs
  src/Stream/src/Abstractions/Attributes/EnableBindingAttribute.cs
  src/Stream/src/Abstractions/Attributes/InputAttribute.cs
  src/Stream/src/Abstractions/Attributes/OutputAttribute.cs
  src/Stream/src/Abstractions/Attributes/StreamListenerAttribute.cs
  src/Stream/src/Stream/Attributes/BinderAttribute.cs
  src/Stream/src/Stream/Extensions/EnableBindingsExtensions.cs
Labels: ReleaseLine/4.x, Type/code-quality

#991 Add Structured message processor
  src/Logging/src/Abstractions/DynamicLoggerProviderBase.cs
  src/Logging/src/Abstractions/MessageProcessingLogger.cs
  src/Logging/src/Abstractions/Properties/AssemblyInfo.cs
  src/Logging/src/Abstractions/StructuredMessageProcessingLogger.cs
  src/Logging/src/DynamicSerilog/SerilogDynamicProvider.cs
  src/Logging/test/DynamicSerilog.Test/SerilogDynamicLoggerProviderTest.cs
  src/Logging/test/DynamicSerilog.Test/serilogSettings.json
Labels: Component/Management
