Repository SteeltoeOSS/Steeltoe, pull requests merged in 2024-04, with the labels that each got.

#1261 #1016 ensure all packages have tags
  shared-package.props
  src/Common/src/Abstractions/Steeltoe.Common.Abstractions.csproj
  src/Common/src/Common.Http/Steeltoe.Common.Http.csproj
  src/Common/src/Common.Net/Steeltoe.Common.Net.csproj
  src/Common/src/Common.Security/Steeltoe.Common.Security.csproj
  src/Common/src/Common.Utils/Steeltoe.Common.Utils.csproj
  src/Common/src/Common/Steeltoe.Common.csproj
  src/Configuration/src/Abstractions/Steeltoe.Configuration.Abstractions.csproj
  src/Connectors/src/Abstractions/Steeltoe.Connectors.Abstractions.csproj
  src/Discovery/src/Abstractions/Steeltoe.Discovery.Abstractions.csproj
  src/Discovery/src/Client/Steeltoe.Discovery.Client.csproj
  src/Discovery/src/Consul/Steeltoe.Discovery.Consul.csproj
  src/Discovery/src/Eureka/Steeltoe.Discovery.Eureka.csproj
  src/Logging/src/Abstractions/Steeltoe.Logging.Abstractions.csproj
  src/Logging/src/DynamicLogger/Steeltoe.Logging.DynamicLogger.csproj
  src/Logging/src/DynamicSerilog/Steeltoe.Logging.DynamicSerilog.csproj
  src/Management/src/Abstractions/Steeltoe.Management.Abstractions.csproj
  src/Management/src/Prometheus/Steeltoe.Management.Prometheus.csproj
Labels: ReleaseLine/4.x

#1276 Prevent adding PlaceholderResolver multiple times
  src/Configuration/src/Placeholder/PlaceholderConfigurationExtensions.cs
  src/Configuration/test/Placeholder.Test/PlaceholderConfigurationExtensionsTest.cs
Labels: Type/enhancement, Component/Configuration, ReleaseLine/4.x

#1278 Update OpenTelemetry packages
  shared-package.props
  shared-test.props
  src/Common/src/Abstractions/ITracingOptions.cs
  src/Common/src/Common/TracingOptions.cs
  src/Management/src/Tracing/Steeltoe.Management.Tracing.csproj
  src/Management/src/Tracing/TracingBaseServiceCollectionExtensions.cs
  src/Management/src/Tracing/TracingCoreServiceCollectionExtensions.cs
  src/Management/src/Wavefront/Exporters/TagExtensions.cs
  versions.props
Labels: Type/enhancement, ReleaseLine/4.x
