Repository SteeltoeOSS/Steeltoe, pull requests merged in 2025-06, with the labels that each got.

#1521 Align Cloud Controller response handling with Spring, improve tests
  src/Common/src/Common/Extensions/ExceptionExtensions.cs
  src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs
  src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs
  src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudControllerPermissionsMock.cs
  src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs
  src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs
  src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs
  src/Management/test/Endpoint.Test/SpringBootAdminClient/FakeServer.cs
Labels: Component/Management, ReleaseLine/4.x

#1531 Fix links for Redis broker
  src/Configuration/src/CloudFoundry/ServiceBindings/PostProcessors/RedisCloudFoundryPostProcessor.cs
  src/Steeltoe.All.sln.DotSettings
Labels: Component/Connectors, ReleaseLine/4.x

#1530 Add GHA workflow for Code Style
  .github/workflows/verify-code-style.yml
Labels: ReleaseLine/4.x
